version: "3.5"
services:
  
  db:
    container_name: project-mongodb
    image: mongo
    ports:
      - 27018:27017
    #volumes:
    #  - ./volumes/mongo/:/data/db:cached
    networks:
      - project

networks:
  project:
    name: project-network
